### ISSUE TITLE
Unable to pickle vcf record

### ISSUE THREAD

**Issue by jdeligt** [jamescasbon/PyVCF#191] opened 2015-02-19 09:57 UTC
I'm trying to use vcf records in a multiprocess script.
But python cannot pickle the record class.

```
Traceback
    job.get()
File "/xx/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
cPickle.PicklingError: Can't pickle <class 'vcf.model.CallData'>: attribute lookup vcf.model.CallData failed
```

It would be good to adjust the __str__(self) to match the form used in the writer module:
```python
        ffs = self._map(str, [record.CHROM, record.POS, record.ID, record.REF]) \
              + [self._format_alt(record.ALT), record.QUAL or '.', self._format_filter(record.FILTER),
                 self._format_info(record.INFO)]
```
This would allow people to at least pass this string between processes and enable multi threading.

**Comment by martijnvermaat** [comment] 2015-02-20 13:59
Hi Joep, thanks for your report.

Though I must say I don't really understand, since I can pickle records just fine (and also their calls and calldata):

```python
>>> import cPickle
>>> from vcf import Reader
>>> record = next(Reader(filename='vcf/test/example-4.1.vcf'))
>>> print cPickle.loads(cPickle.dumps(record))
Record(CHROM=20, POS=14370, REF=G, ALT=[A])
```

Are you perhaps using the multiprocessing infrastructure over different machines (e.g., using IPython parallel) where you need to make sure the appropriate modules are imported on the remote end as well?

**Comment by jdeligt** [comment] 2015-02-21 12:51
I am indeed using the multiprocessing module.
If there is a known fix that would be great. The Internet was not very
helpful in this case.

**Comment by martijnvermaat** [comment] 2015-02-21 19:04
If you could share some code (as short as possible) that reproduces the issue I can perhaps get a better idea of what the problem is.

**Comment by jdeligt** [comment] 2015-02-21 19:39
Hi, 

I'll make a minimal set to reproduce the problem on monday.
My current work-around and script I'm using it in is here:
https://github.com/jdeligt/Genetics/blob/master/Annotate_CADD_Scores_In_VCF.py

It's the return of the function:
def extract_CADD_score(arguments, q):

When I return vcd_record (rather than the String that I now generate) raises the error that I supplied.
So when this function returns a VCF record it doesn't work.

Best,

Joep

**Comment by jdeligt** [comment] 2015-02-23 12:39
Please find the minimal script here:
https://github.com/jdeligt/Genetics/blob/master/MultiprocessVCF.py

Call:
python2.7 ~/git/Genetics/MultiprocessVCF.py --vcf test.vcf.gz


Traceback:
-------------------------------------------------------------------------------------------
Checking files
Filling Queue
Starting listener
Collecting results

Traceback (most recent call last):
  File "/Users/test/git/Genetics/MultiprocessVCF.py", line 85, in <module>
    main()
  File "/Users/test/git/Genetics/MultiprocessVCF.py", line 75, in main
    job.get()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value

cPickle.PicklingError: Can't pickle <class 'vcf.model.CallData'>: attribute lookup vcf.model.CallData failed
-------------------------------------------------------------------------------------------

Best,

Joep

**Comment by martijnvermaat** [comment] 2015-02-25 16:57
Thanks, I'll have a look (but it might not be this week).

**Comment by jdeligt** [comment] 2015-02-25 17:02
Thanks.
And the workaround works so no pressing matter.

**Comment by martijnvermaat** [comment] 2015-03-10 22:37
@jdeligt I had a look at this. Short answer: it seems difficult to solve.

The problem is that the `CallData` class is defined dynamically at runtime for each record (so there's actually not just one `CallData`). Pickle expects the class definition for these classes at `vcf.model.CallData` but of course it's not there (it exists only in the local scope of `vcf.model.make_calldata_tuple`).

It might be possible to workaround this by adding these definitions to the global `vcf.model` namespace (adding it to `globals()`), but they would have to be named uniquely (which should also be assigned to `CallData.__name__`), probably based on the current record coordinates or randomly generated. This will get *really* hairy and I don't think we want to go there.

(I'm still not completely sure why my toy example above does work by the way.)

For your specific problem, I would advise to extract the data from the VCF record that you need and only put that on the queue.

I'm closing this now, but feel free to reopen if you have additional thoughts on the issue.

**Closed by martijnvermaat** 2015-03-10 22:37 UTC

**Comment by jdeligt** [comment] 2015-03-11 08:54
Hi,

Thanks for the info and trouble.
The workaround you mention is also what I use now. The hairy thing there is
that I have to use an additional writer object to get the proper
formatting. And I had to hack into some of its class functions.

I.e. There's no neat way to format a record as a string without directly
writing it (as far as I could tell) . This seems like something which would
be good to have and would also solve this problem.

I'll leave the ticket closed since there is a workaround but if time
permits it might be worth looking into.

Best,
Joep

**Comment by martijnvermaat** [comment] 2015-03-11 12:22
I agree. The writer is not much more than a quick hack, but that would be another issue.
